name: prod-deploy-requiring-approval

on:
  push:

jobs:
  staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Staging Release!"

  prod:
    needs:
      - staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Production Release!"
